# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mate-hive
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
